### ISSUE TITLE
Embedded images not clickable

### ISSUE THREAD

**Issue by illusionyy** [Sylhare/Jekyll-theme#319]
More of a feature request, as title says, when embedding images, they're not clickable and does not open in new tab. It can only be done using right click (on desktop) or hold on image (on mobile) which is inconvenient for posts with a lot of images which needs zoomed in viewing.

Sidenote: awesome theme and design :)

**Comment by im-coder-lg** [comment]
Well, that is a good idea but Markdown supports it. If you wrap an image link with the normal link syntax as you do in SVGs, you can create a redirecting photo that will redirect users to the link(here, the image). You have to test it locally so that you get the slug but after that, it's a cakewalk.

**Comment by sylhare** [comment]
Then I see no issue
