### ISSUE TITLE
"There are no blog posts", when installing gem into new Jekyll project 

### ISSUE THREAD

**Issue by elmar-hinz** [Sylhare/Jekyll-theme#320]
I try to check out the gem "type-on-strap" with a fresh Jekyll installation, which contains one default post from today. _Type-on-strap_ shows "There are no blog posts". 

Searching the sources this comes form __includes/blog/blog.html_ , which iterates _paginator.posts_. The gems description names a runtime dependency _jekyll-paginate_. Even installing this gem manually doesn't get it running. _jekyll-paginate_ was last updated three years ago and has few description.

At this point I give up. At least the initial installation should run out-of-the-box. 

* ruby 3.0.2
* jekyll 4.2.1

Steps to reproduce:

```
jekyll new testproject 
cd testproject/
bundler remove minima
 bundler add webrick type-on-strap
 # edit _conf.yml: Set theme to type-on-strap.
 jekyll serve -w
```

```
# check that there is one post
 ls -al  _posts/

``` 
<img width="572" alt="Screenshot 2021-10-10 at 15 16 15" src="https://user-images.githubusercontent.com/1227339/136697480-61d673d4-45dd-4002-9424-60d586e576df.png">

**Comment by im-coder-lg** [comment]
First off, @sylhare you have literally _locked_ down the gem. I mean, just spin up a Gitpod environment, use the terminal and try pulling the latest gem package and it asks you to log in. You can log in to the RubyGems package environment but I can't. I tried that and it is of no use. I can't pull the gem since you need to give me perms to get the gem pulled on. Maybe you set something up in your Packages settings and it is behaving like that.
